### ISSUE TITLE
離席機能実装

### ISSUE THREAD

**Issue by MomokaHara** [motib8tas/zaseki#12]
# 説明
自分が着席している座席について、離席ボタンを押すと離席できるようにする。
離席ボタンは自分が座っている座席にのみ表示される

# 対応
- [ ] 自分が座っている座席にのみ離席ボタンを表示する
- [ ] 離席ボタン押下時、離席APIを呼び出しDBの今日日付、該当座席番号の着席者名を削除する

**Comment by zygo-sem** [comment]
@tomoyaki 
クローズしてよい？

**Comment by tomoyaki** [comment]
おけ。クローズします。
