### ISSUE TITLE
ログインしているユーザの着席状態をどうやって管理するか？

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#26]
ここの実装、ちょっと考えたい。
着席フラグでよいのか、ログインユーザが座っている座席IDを持たせる必要がないか？を気にしています。（前にSlackに投下した実装検討したとき＊は、座席IDを持たせようとしていた。）
＊：https://untitled-geh5982.slack.com/archives/C0473MGJCMD/p1680534094917739

_Originally posted by @tomoyaki in https://github.com/motib8tas/zaseki/pull/25#discussion_r1167022298_

**Comment by zygo-sem** [comment]
いまはflagで管理している

**Comment by tomoyaki** [comment]
個人的には、動くのでこのままでもいいと思っている。
