### ISSUE TITLE
プロフィール編集モーダルのUIカイゼン

### ISSUE THREAD

**Issue by tomoyaki** [motib8tas/zaseki#28]
- [x] プロフィール編集モーダルの上限の余白を設けたい
- [ ] プロフィール編集モーダルをスマホで開いた際のサイズを調整したい
- [ ] プロフィール編集モーダルを表示中に、背景をクリックするとモーダルを閉じるようにしたい

**Comment by tomoyaki** [comment]
「プロフィール編集モーダルを表示中に、背景をクリックするとモーダルを閉じるようにしたい」
はたぶん簡単な修正なので、やりやすいと思います。

**Comment by zygo-sem** [comment]
プロフィール編集モーダルを表示中に、背景をクリックするとモーダルを閉じるようにしたい
だけど、文字入力しているときに、エンターではなく、他の場所クリックする人もいると思ってて、
その人が枠外タップしたら入力したものがリセットされるから、個人的にはいらないかなあとも思ってる。

@horinodai67 @MomokaHara 
意見ちょうだい！

**Comment by horinodai67** [comment]
> > プロフィール編集モーダルを表示中に、背景をクリックするとモーダルを閉じるようにしたい
> 
> 文字入力しているときに、エンターではなく、他の場所クリックする人もいると思ってて、 その人が枠外タップしたら入力したものがリセットされるから、個人的にはいらないかなあとも思ってる。

「枠外タップしたら入力したものがリセットされる」を再現できなかったのですが、背景をクリックしたら入力中の項目がリセットされるということですか？
あと、背景タップでモーダルを閉じるというのは（特に今のスマホの画面だと）あった方がいいなと思います。スマホだとモーダル閉じれないので、（画面が切れてる等それ以前の問題もありますが）
