### ISSUE TITLE
ローディング機能実装

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#31]
# 背景

現状、ログイン後に一瞬白画面が表示されて、座席が完全に読み込まれてから表示される。

# 対応

ログイン後、座席情報の読み込み中はローディング中を表すぐるぐるマークを表示し、座席の描画が完了したら座席を表示する。

# 参考リンク

https://qiita.com/saka_rinta/items/3eeff96dd3d090051f6d

**Comment by tomoyaki** [comment]
ぐるぐるのやつ

**Comment by tomoyaki** [comment]
しんぷるにこれ実装すればよさそうね。
https://vuetifyjs.com/en/components/progress-circular/

個人的には、ローディングマークのカラーはプライマリーの青（ヘッダと同じ）か、モノトーンにしたい。（＝使う色をここで増やしたくない）
