### ISSUE TITLE
Amplifyの認証コード認証画面の日本語化

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#32]
# 背景
現状、ログイン画面＞新規登録ボタンを押した後の認証コード認証画面が英語になっている。
# 対応
- [ ] 上記画面を日本語化する。

**Comment by tomoyaki** [comment]
個人的には、ログイン画面の「ログイン」という文言も、「座席表にログイン」にしたい。

**Comment by tomoyaki** [comment]
さすがに英語わからん人はいないと思うが、部全体に公開する手前、日本語化はMUSTかなぁ。
