### ISSUE TITLE
画面更新ボタンの設置

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#33]
~~router.reload()にすると、画面がリフレッシュする感じになるから、mountedにあるaxiosの取得をもう一回ここでやる方がいいと思うが、要検討~~

**Comment by tomoyaki** [comment]
- 一番作り込むとするなら、自動更新を実装
- 一番簡易なのは、F5を押してねということが伝わるようにする

**Comment by zygo-sem** [comment]
AWSの更新ボタンのようなものをつける

**Comment by tomoyaki** [comment]
更新ボタンのイメージ作ります！

**Comment by tomoyaki** [comment]
https://github.com/motib8tas/zaseki/pull/44
で対応完了のため、クローズ。
