### ISSUE TITLE
固定席を固定席の人しか押せないように実装

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#35]
# 背景
現状、固定席の人の座席は誰でもクリック（＝上書き着席）が可能になっている。
固定席の本人のみクリックできるようにしたい。
# 対応
- [x] 固定席の本人のみクリックできるようにする

**Comment by tomoyaki** [comment]
マストで対応必要

**Comment by horinodai67** [comment]
とりあえずトライしてみます！

**Comment by horinodai67** [comment]
完了です。
