### ISSUE TITLE
固定席で離席している人のボタン表示を実装する

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#36]
# 背景
固定席で離席している人は「氏名、会社名、内線番号が表示されているが、薄い状態」とする。（figma参照）
現状、固定席の人は`seatedStatus`=`true`で氏名等が表示される状態になっている。
# 対応
- [x] figma通りに実装する。

**Comment by tomoyaki** [comment]
固定席で離席している人のイメージは、figmaみてくれればOK。
氏名、会社名、内線番号が表示されているが、薄い状態。
https://www.figma.com/file/taD8qGSYuHg00MyoV52fTK/seat-map?type=design&node-id=12299-70&t=qLWJqU24z3ZVIOEw-4

**Comment by tomoyaki** [comment]
`seatedStatus`が`false`であっても、固定席の場合は氏名とうの情報を表示するように変更する必要がありますね。

**Comment by tomoyaki** [comment]
https://github.com/motib8tas/zaseki/pull/47
で対応済。クローズ。
