### ISSUE TITLE
リリース準備

### ISSUE THREAD

**Issue by MomokaHara** [motib8tas/zaseki#50]
リリースに向けて必要なタスク

- [ ] デプロイ（Amplifyで可能？）
- [ ] IPアドレス取得（本部AWSにElastic IP申請していたっけ？）
- [ ] ドメイン取得（IP直打ちでアクセスさせるなら不要）
- [ ] Route53設定（IP直打ちでアクセスさせるなら不要）
- [ ] 紹介資料作成
- [ ] 各座席に「座席表リニューアルリリースのお知らせ」を貼りたい
　→全体同報向けのメールはフォルダ振り分けの設定上見てない人もいるため。
　　この時点でQRまで貼れたら尚良い。

**Comment by tomoyaki** [comment]
完了
