### ISSUE TITLE
固定席ユーザーが自分の席に着席しようとしても、1回目の座席クリックでは、着席処理が行われない不具合の解消

### ISSUE THREAD

**Issue by horinodai67** [motib8tas/zaseki#60]
## 現象

- 固定席ユーザーが自分の席に着席しようとしても、1回目の座席クリックでは、着席処理が行われない
- 2回目のクリックでは、着席処理が行われる

## 原因

- テーブル取得の際に着席情報にログインユーザのemployIDがある場合、sitDownFlagをtrueとしているため、固定席ユーザーはログイン時sitDownFlagがtrueであり、フロント側では着席していることになっている。そのため、初回クリックでは、離席処理が行われてしまっている。
`this.seats.find((object) => {
          if (object.employeeId == this.loginUserEmployeeId) {
            this.sitDownFlag = true;
            console.log(this.sitDownFlag);
          } else {
            return;
          }`

## 対処方法

findメソッドの条件を
`object.employeeId == this.loginUserEmployeeId`
かつ
`seatStatus == true`
とする。

**Comment by zygo-sem** [comment]
クローズします。
