### ISSUE TITLE
文字数によるCSSの変更

### ISSUE THREAD

**Issue by zygo-sem** [motib8tas/zaseki#66]
名前が長い人が枠からはみ出すから以下の対応を取りたい

- 指定した文字数以上の文字列の場合、文字数が長い人用のCSSを割り当てる

![Screenshot 2023-06-01 18 48 32](https://github.com/motib8tas/zaseki/assets/83294806/03de0abe-59b9-4976-b5e6-6ac8142bb821)

**Comment by tomoyaki** [comment]
#71 で対応中。
