### ISSUE TITLE
「チーム名」を削除する

### ISSUE THREAD

**Issue by MomokaHara** [motib8tas/zaseki#8]
# 説明
初期ユーザデータ登録を各自で行ってもらうため、初期ユーザ登録機能実装する。

# 対応
- [x] 画面項目の検討（会社メアド、PW、姓、名、内線番号、所属（プルダウン）で良いか）
- [x] 初めての方はこちら画面の作成
- [x] 入力されたデータをAWSに登録（認証コードを登録アドレスに送信して登録する？）
- [x] 作成したユーザでログインができる

**Comment by zygo-sem** [comment]
残：チーム名

**Comment by tomoyaki** [comment]
チーム名は座席ボタンへの出し方が未決のため、一旦見送る。コード上からチーム名を削除する対応が必要。
@zygo-sem 
お願いしてもいいですか？

**Comment by zygo-sem** [comment]
対応したのでクローズします
